version: 2
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    insecure-external-code-execution: allow
  - package-ecosystem: npm
    directory: "/lang/typescript"
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Can not bump past v1.5.1 until https://github.com/changesets/action/issues/501 is fixed
      - dependency-name: "changesets/action"
        versions: [">=1.5.1"]
