version: 2
registries:
  ruby-shopify:
    type: rubygems-server
    url: https://pkgs.shopify.io/basic/gems/ruby
    username: ${{secrets.RUBYGEMS_SERVER_PKGS_SHOPIFY_IO_USERNAME}}
    password: ${{secrets.RUBYGEMS_SERVER_PKGS_SHOPIFY_IO_PASSWORD}}
  github-com:
    type: git
    url: https://github.com
    username: ${{secrets.DEPENDENCIES_GITHUB_USER}}
    password: ${{secrets.DEPENDENCIES_GITHUB_TOKEN}}
updates:
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 100
    insecure-external-code-execution: allow
    registries: "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    ignore:
      # Can not bump past v1.5.1 until https://github.com/changesets/action/issues/501 is fixed
      - dependency-name: "changesets/action"
        versions: [">=1.5.1"]
