name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} / ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        gemfile:
         - Gemfile
        ruby: ["3.2", "3.3", "3.4"]
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    steps:
    - name: Check out code
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@a30dfa457ad68707b8b910ac3a244714b61c0626 # v1.320.0
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: RuboCop
      run: bin/style
    - name: Tests
      run: bin/test
    - name: CLDR Rake Tasks Integration Test
      run: bin/test-cldr-rake-tasks

